name: Mini-Piston Full CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, minikube]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ansible (if missing)
      run: |
        if ! command -v ansible >/dev/null; then
          sudo apt update && sudo apt install -y ansible
        fi

    - name: Validate environment using Ansible
      run: ansible-playbook ansible/validate.yml

    - name: Use Minikube Docker daemon
      run: |
        eval $(minikube docker-env)
        docker info | grep Name

    - name: Build Mini-Piston image
      run: |
        eval $(minikube docker-env)
        docker build -t mini-piston:latest .

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/deployment.yaml

    - name: Restart API deployment
      run: |
        kubectl rollout restart deployment piston-api
        kubectl rollout status deployment piston-api
